import Head from "next/head";
import {Header} from "../components/Header";
import Navbar from "../components/Navbar";
import Movies from "../components/Movies";
import requests from "../utils/requests";

// Rendered for Client
export default function Home({results}) {
	return (
		<div>
			<Head>
				<title>Auggiez</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* Header */}
			<Header />
			{/* Navbar */}
			<Navbar />
			{/* Movie Body */}
			<Movies results={results} />
		</div>
	);
}

// Rendered for Server - Happens first then rendered to the client
export async function getServerSideProps(context) {
	const genre = context.query.genre;

	const request = await fetch(
		`https://api.themoviedb.org/3${
			requests[genre]?.url || requests.fetchTrending.url
		}`
	).then((res) => res.json());

	return {
		props: {
			results: request.results,
		},
	};
}
